use_frameworks!

platform :ios, '9.0'

target 'pixalate-prebid-blocking_Example' do
  pod 'prebid-blocking', :path => '../'

  target 'pixalate-prebid-blocking_Tests' do
    inherit! :search_paths

    
  end
end
